// Copyright 2022-2023 The Nephio Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: hydration.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/nephio-project/nf-deploy-controller/api/v1alpha1"
)

// MockHydrationInterface is a mock of HydrationInterface interface.
type MockHydrationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHydrationInterfaceMockRecorder
}

// MockHydrationInterfaceMockRecorder is the mock recorder for MockHydrationInterface.
type MockHydrationInterfaceMockRecorder struct {
	mock *MockHydrationInterface
}

// NewMockHydrationInterface creates a new mock instance.
func NewMockHydrationInterface(ctrl *gomock.Controller) *MockHydrationInterface {
	mock := &MockHydrationInterface{ctrl: ctrl}
	mock.recorder = &MockHydrationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydrationInterface) EXPECT() *MockHydrationInterfaceMockRecorder {
	return m.recorder
}

// CreateNFDeployActuators mocks base method.
func (m *MockHydrationInterface) CreateNFDeployActuators(ctx context.Context, nfDeploy v1alpha1.NfDeploy) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNFDeployActuators", ctx, nfDeploy)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNFDeployActuators indicates an expected call of CreateNFDeployActuators.
func (mr *MockHydrationInterfaceMockRecorder) CreateNFDeployActuators(ctx, nfDeploy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNFDeployActuators", reflect.TypeOf((*MockHydrationInterface)(nil).CreateNFDeployActuators), ctx, nfDeploy)
}

// Hydrate mocks base method.
func (m *MockHydrationInterface) Hydrate(ctx context.Context, nfDeploy v1alpha1.NfDeploy) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hydrate", ctx, nfDeploy)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hydrate indicates an expected call of Hydrate.
func (mr *MockHydrationInterfaceMockRecorder) Hydrate(ctx, nfDeploy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hydrate", reflect.TypeOf((*MockHydrationInterface)(nil).Hydrate), ctx, nfDeploy)
}
